### ISSUE TITLE
Chose meal on Weekday and save

### ISSUE THREAD

**Issue by benjamintautfest** [benjamintautfest/capstone-project#1]

**Comment by benjamintautfest** [comment]
### Value statement

As a person
I need the posibility to save a recipe for a given weekday

### Description
<img width="402" alt="grafik" src="https://user-images.githubusercontent.com/544199/99289422-38715680-283d-11eb-9ce2-4940e4175b11.png">


### Acceptance criteria

Several recipes must be available and possible to be saved

### Tasks

- [ ] Create feature branch
- [ ] Write test
- [ ] Create aprox. 7 recipe titles as a list to chose from
- [ ] Create basic functionality to save recipe for each day
- [ ] Add Styles


### Complexity
low - medium
