### ISSUE TITLE
generate shopping list

### ISSUE THREAD

**Issue by benjamintautfest** [benjamintautfest/capstone-project#3]

**Comment by benjamintautfest** [comment]
### Value statement

As a person
I need save the ingredients for any given recipe and save it to a shopping list

### Description


<img width="234" alt="grafik" src="https://user-images.githubusercontent.com/544199/99254506-bf5d0980-2812-11eb-8042-e0386a45435b.png">



### Acceptance criteria

All the ingredients of a recipe must be saved in a shopping list
There must be a page where the shopping list is displayed.

### Tasks

- [ ] Create feature branch
- [ ] Write shopping list component
- [ ] Write test
- [ ] Create basic functionality to save ingredients 
- [ ] Add routing to be able to switch to shopping list page
- [ ] Add Styles



### Complexity
medium
