### ISSUE TITLE
Add Page with recipe

### ISSUE THREAD

**Issue by benjamintautfest** [benjamintautfest/capstone-project#7]

**Comment by benjamintautfest** [comment]
### Value statement

As a person
I have to be able to read the recipe i chose

### Description
Recipe page

<img width="302" alt="grafik" src="https://user-images.githubusercontent.com/544199/99247960-05f93680-2808-11eb-9426-980052a48562.png">

### Acceptance criteria

recipe must be available and possible to be saved

### Tasks


- [ ] Create feature branch
- [ ] Create recipe component
- [ ] Add picture or placeholder if not available
- [ ] Add basic navigation for access to recipe page and back home
- [ ] Write test
- [ ] Add Styles


### Complexity
low
